# 错误处理

viem 中的每个模块都导出了一个相应的错误类型，你可以使用它来强类型化你的 `catch` 语句。

这些类型的形式为 `<Module>ErrorType`。例如，`getBlockNumber` 操作导出了一个 `GetBlockNumberErrorType` 类型。

不幸的是，[TypeScript 并没有对类型化异常的抽象](https://github.com/microsoft/TypeScript/issues/13219) ，因此最务实和常规的方法是在 `catch` 语句中显式地转换错误类型。

:::code-group

```ts [example.ts] twoslash
// @noErrors
// @filename: client.ts
import { createPublicClient, http } from 'viem'
import { mainnet } from 'viem/chains'

export const client = createPublicClient({
  chain: mainnet,
  transport: http()
})
// @filename: index.ts
// ---cut---
import { type GetBlockNumberErrorType } from 'viem'
import { client } from './client'

try {
  const blockNumber = await client.getBlockNumber()
} catch (e) {
  const error = e as GetBlockNumberErrorType
  error.name 
//      ^?






  if (error.name === 'InternalRpcError')
    error.code
    //    ^?


  if (error.name === 'HttpRequestError') {
    error.headers
    //    ^?


    error.status
    //    ^?
  }
}
```

```ts [client.ts]
import { createPublicClient, http } from 'viem'
import { mainnet } from 'viem/chains'

export const publicClient = createPublicClient({
  chain: mainnet,
  transport: http()
})
```

:::